services:
  # IdentityGenerator
  Preventool\Infrastructure\Persistence\IdentityGenerator\UuidIdentityGenerator: ~
  Preventool\Domain\Shared\Model\IdentityGenerator: '@Preventool\Infrastructure\Persistence\IdentityGenerator\UuidIdentityGenerator'

  # Repositories
  Preventool\Infrastructure\Persistence\Doctrine\Repository\Demo\DoctrineDemoRepository: ~
  Preventool\Domain\Demo\Repository\DemoRepository: '@Preventool\Infrastructure\Persistence\Doctrine\Repository\Demo\DoctrineDemoRepository'

  Preventool\Infrastructure\Persistence\Doctrine\Repository\User\DoctrineUserRepository: ~
  Preventool\Domain\User\Repository\UserRepository: '@Preventool\Infrastructure\Persistence\Doctrine\Repository\User\DoctrineUserRepository'

  Preventool\Infrastructure\Persistence\Doctrine\Repository\Admin\DoctrineAdminRepository: ~
  Preventool\Domain\Admin\Repository\AdminRepository: '@Preventool\Infrastructure\Persistence\Doctrine\Repository\Admin\DoctrineAdminRepository'
