services:
  # IdentityGenerator
  Preventool\Infrastructure\Persistence\IdentityGenerator\UuidIdentityGenerator: ~
  Preventool\Domain\Shared\Model\IdentityGenerator: '@Preventool\Infrastructure\Persistence\IdentityGenerator\UuidIdentityGenerator'

  # Repositories
  Preventool\Infrastructure\Persistence\Doctrine\Repository\Demo\DoctrineDemoRepository: ~
  Preventool\Domain\Demo\Repository\DemoRepository: '@Preventool\Infrastructure\Persistence\Doctrine\Repository\Demo\DoctrineDemoRepository'

  Preventool\Infrastructure\Persistence\Doctrine\Repository\User\DoctrineUserRepository: ~
  Preventool\Domain\User\Repository\UserRepository: '@Preventool\Infrastructure\Persistence\Doctrine\Repository\User\DoctrineUserRepository'

  Preventool\Infrastructure\Persistence\Doctrine\Repository\Admin\DoctrineAdminRepository: ~
  Preventool\Domain\Admin\Repository\AdminRepository: '@Preventool\Infrastructure\Persistence\Doctrine\Repository\Admin\DoctrineAdminRepository'

  Preventool\Infrastructure\Persistence\Doctrine\Repository\Company\DoctrineCompanyRepository: ~
  Preventool\Domain\Company\Repository\CompanyRepository: '@Preventool\Infrastructure\Persistence\Doctrine\Repository\Company\DoctrineCompanyRepository'

  Preventool\Infrastructure\Persistence\Doctrine\Repository\Workplace\DoctrineWorkplaceRepository: ~
  Preventool\Domain\Workplace\Repository\WorkplaceRepository: '@Preventool\Infrastructure\Persistence\Doctrine\Repository\Workplace\DoctrineWorkplaceRepository'

  Preventool\Infrastructure\Persistence\Doctrine\Repository\Company\DoctrineHealthAndSafetyPolicyRepository: ~
  Preventool\Domain\Company\Repository\HealthAndSafetyPolicyRepository: '@Preventool\Infrastructure\Persistence\Doctrine\Repository\Company\DoctrineHealthAndSafetyPolicyRepository'

  Preventool\Infrastructure\Persistence\Doctrine\Repository\BaselineStudy\DoctrineBaselineStudyRepository: ~
  Preventool\Domain\BaselineStudy\Repository\BaselineStudyRepository: '@Preventool\Infrastructure\Persistence\Doctrine\Repository\BaselineStudy\DoctrineBaselineStudyRepository'