services:
  # Repositories
  Preventool\Infrastructure\Persistence\Doctrine\Repository\Demo\DoctrineBaseRepository: ~
  Preventool\Domain\Demo\Repository\DemoRepository: '@Preventool\Infrastructure\Persistence\Doctrine\Repository\Demo\DoctrineDemoRepository'


#  App\Domain\User\Repository\UserRepository: '@App\Infrastructure\Persistence\Doctrine\Repository\User\MysqlDoctrineUserRepository'
#  App\Domain\Admin\Repository\AdminRepository: '@App\Infrastructure\Persistence\Doctrine\Repository\Admin\MysqlDoctrineAdminRepository'