api_login_check:
  path: /api/login_check

#shared
get_session:
  path: /api/v1/session
  controller: App\Controller\Shared\Session\GetSessionController
  methods: [GET]
get_company_session:
  path: /api/v1/company-session/{id}
  controller: App\Controller\Shared\Session\GetCompanySessionController
  methods: [GET]

#Demo
get_demo:
  path: /api/v1/demo
  controller: App\Controller\Demo\GetDemoController
  methods: [GET]

#Admin
post_create_admin:
  path: /api/v1/admin
  controller: App\Controller\Admin\CreateAdminController
  methods: [POST]
search_admin:
  path: /api/v1/admin
  controller: App\Controller\Admin\SearchAdminController
  methods: [GET]
get_admin:
  path: /api/v1/admin/{id}
  controller: App\Controller\Admin\GetAdminByIdController
  methods: [GET]
put_update_admin:
  path: /api/v1/admin/{id}
  controller: App\Controller\Admin\UpdateAdminController
  methods: [PUT]
put_update_admin_password:
  path: /api/v1/admin/{id}/password
  controller: App\Controller\Admin\UpdateAdminPasswordController
  methods: [PUT]


#Company
post_create_company:
  path: /api/v1/company
  controller: App\Controller\Company\CreateCompanyController
  methods: [POST]

get_company:
  path: /api/v1/company/{id}
  controller: App\Controller\Company\GetCompanyByIdController
  methods: [GET]
search_company:
  path: /api/v1/company
  controller: App\Controller\Company\SearchCompanyController
  methods: [GET]
put_update_company:
  path: /api/v1/company/{id}
  controller: App\Controller\Company\UpdateCompanyController
  methods: [PUT]
post_upload_health_and_safety_policy_document_of_company:
  path: /api/v1/company/{id}/upload-health-and-safety-policy
  controller: App\Controller\Company\UploadHealthAndSafetyPolicyController
  methods: [POST]
get_comany_health_and_safety_policy:
  path: api/v1/company/{id}/health-and-safety-policy
  controller: App\Controller\Company\GetHealthAndSafetyPolicyController
  methods: [GET]
get_comany_document_health_and_safety_policy:
  path: api/v1/company/{id}/document-health-and-safety-policy
  controller: App\Controller\Company\GetDocumentHealthAndSafetyPolicyController
  methods: [GET]
put_company_approve_health_and_safety_policy:
  path: api/v1/company/{id}/approve-health-and-safety-policy
  controller: App\Controller\Company\PutApproveHealthAndSafetyPolicyController
  methods: [PUT]



#Workplace
post_create_workplace:
  path: api/v1/company/{companyId}/workplace
  controller: App\Controller\Workplace\CreateWorkplaceController
  methods: [POST]
search_workplace:
  path: /api/v1/workplace
  controller: App\Controller\Workplace\SearchWorkplaceController
  methods: [GET]
get_company_workplace_by_id:
  path: /api/v1/company/{companyId}/workplace/{workplaceId}
  controller: App\Controller\Workplace\GetWorkplaceByIdController
  methods: [GET]
put_update_workplace:
  path: /api/v1/company/{companyId}/workplace/{id}
  controller: App\Controller\Workplace\UpdateWorkplaceController
  methods: [PUT]

#BaselineStudy
get_base_line_study_indicators:
  path: /api/v1/baseline-study-indicators
  controller: App\Controller\BaselineStudy\GetBaselineStudyIndicatorsController
  methods: [GET]
get_workplace-baseline-study_indicators-by-catageory:
  path: /api/v1/workplace-baseline-study-indicators-by-category/{workplaceId}/{category}
  controller: App\Controller\BaselineStudy\GetWorkplaceBaselineStudyIndicatorsByCategoryController
  methods: [GET]

#AuditType
post_create_auditType:
  path: /api/v1/audit-type
  controller: App\Controller\AuditType\CreateAuditTypeController
  methods: [POST]
get_auditType:
  path: /api/v1/audit-type/{id}
  controller: App\Controller\AuditType\GetAuditTypeController
  methods: [GET]
search_auditType:
  path: /api/v1/audit-type
  controller: App\Controller\AuditType\SearchAuditTypeController
  methods: [GET]



