api_login_check:
  path: /api/login_check

#shared
get_session:
  path: /api/v1/session
  controller: App\Controller\Shared\Session\GetSessionController
  methods: [GET]
get_company_session:
  path: /api/v1/company-session/{id}
  controller: App\Controller\Shared\Session\GetCompanySessionController
  methods: [GET]

#Demo
get_demo:
  path: /api/v1/demo
  controller: App\Controller\Demo\GetDemoController
  methods: [GET]

#Admin
post_create_admin:
  path: /api/v1/admin
  controller: App\Controller\Admin\CreateAdminController
  methods: [POST]
search_admin:
  path: /api/v1/admin
  controller: App\Controller\Admin\SearchAdminController
  methods: [GET]
get_admin:
  path: /api/v1/admin/{id}
  controller: App\Controller\Admin\GetAdminByIdController
  methods: [GET]
put_update_admin:
  path: /api/v1/admin/{id}
  controller: App\Controller\Admin\UpdateAdminController
  methods: [PUT]
put_update_admin_password:
  path: /api/v1/admin/{id}/password
  controller: App\Controller\Admin\UpdateAdminPasswordController
  methods: [PUT]


#Company
post_create_company:
  path: /api/v1/company
  controller: App\Controller\Company\CreateCompanyController
  methods: [POST]

get_company:
  path: /api/v1/company/{id}
  controller: App\Controller\Company\GetCompanyByIdController
  methods: [GET]
search_company:
  path: /api/v1/company
  controller: App\Controller\Company\SearchCompanyController
  methods: [GET]
put_update_company:
  path: /api/v1/company/{id}
  controller: App\Controller\Company\UpdateCompanyController
  methods: [PUT]

#Workplace
post_create_workplace:
  path: api/v1/company/{companyId}/workplace
  controller: App\Controller\Workplace\CreateWorkplaceController
  methods: [POST]


